language: python
cache: pip
dist: xenial
sudo: required
jobs:
  include:
    - name: Run plugin test suite with python 3.7
      python: 3.7
      script: 'pytest'

    - name: Typecheck Django test suite with python 3.7
      python: 3.7
      script: 'python ./scripts/typecheck_tests.py'

    - name: Typecheck Django test suite with python 3.6
      python: 3.6
      script: 'python ./scripts/typecheck_tests.py'

    - name: Mypy for plugin code
      python: 3.7
      script: 'mypy ./mypy_django_plugin'

    - name: Lint with black
      python: 3.7
      script: 'black --check django-stubs/'

    - name: Lint plugin code with flake8
      python: 3.7
      script: 'flake8'

    - name: Lint plugin code with isort
      python: 3.7
      script: 'isort --check --diff'

before_install: |
  sudo apt update
  sudo apt install binutils libproj-dev gdal-bin
  pip install -U pip setuptools wheel
install: |
  pip install -r ./dev-requirements.txt
