version: 2

jobs:
  lint:
    docker:
      - image: circleci/python:3.7-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - django-types-v2-{{ checksum "poetry.lock" }}-{{ checksum "yarn.lock" }}
      - run:
          name: install python dependencies
          command: |
            # Use our new PATH so we can call poetry from bash
            echo 'export PATH="$PATH":"$HOME"/.local/bin' >> $BASH_ENV
            source $BASH_ENV
            python -m pip install --user poetry==1.1.9
            poetry config virtualenvs.in-project true
            poetry --version
            poetry install
      - run:
          name: install node dependencies
          command: |
            yarn install --frozen-lockfile --non-interactive
      - save_cache:
          paths:
            - ./.mypy_cache
            - /root/.cache/
          key: django-types-v2-{{ checksum "poetry.lock" }}-{{ checksum "yarn.lock" }}
      - run:
          name: lint
          command: ./s/lint

workflows:
  version: 2
  test:
    jobs:
      - lint
